project_name: go-sponge
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
nfpms:
- maintainer: Marco Santos <me@marcopsantos.com>
  description: Golang alternative to the already existing sponge cli
  homepage: https://github.com/LOQ9/go-sponge
  license: MIT
  formats:
  - deb
  - rpm
  - apk

archives:
  -
    format: binary